#!/usr/bin/env bash

string_modules='md avi swf wma wmv mpg mpeg mov pdf xsl xslx doc docx ppt pptx zip rar tar gz gz2'

cat > ./src/misc/module.d.ts <<EOF
/**
 * This file is generated by $(basename $0) automatically.
 */
EOF

for name in $string_modules
do
  cat >> ./src/misc/module.d.ts <<EOF

declare module '*.$name' {
  const content: string;
  export default content;
}
EOF
done
